version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: notification_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notificationdb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notification-network

volumes:
  postgres_data:

networks:
  notification-network:
    driver: bridge